name: Deploy Frontend to Fly.io (Production)

on:
  push:
    branches:
      - main
    paths:
      - "fixmymind/**"
      - ".github/workflows/deploy-frontend-prod.yml"

jobs:
  deploy:
    name: Deploy Frontend to Fly.io
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Fly.io CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "${HOME}/.fly/bin" >> $GITHUB_PATH

      - name: Deploy to Fly.io (Frontend)
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          API_URL: ${{ secrets.API_URL_PROD }}
          EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.EXPO_PUBLIC_SUPABASE_URL }}
          EXPO_PUBLIC_SUPABASE_KEY: ${{ secrets.EXPO_PUBLIC_SUPABASE_KEY }}
        run: fly deploy --config fly.toml --remote-only